r"""LaTeX report writer (``results.tex``).

Renders the :class:`~eval3r.reports.table.ReportData` view of a ``RunResult`` as a
LaTeX fragment (``\section`` + ``tabular`` blocks) suitable for ``\input`` into a
paper. Special characters are escaped. The partial-coverage banner is rendered as a
bold warning paragraph so a partial aggregate cannot be pasted into a paper as a
complete one without the warning coming along.
"""

from __future__ import annotations

from pathlib import Path

from eval3r.core.result import RunResult
from eval3r.reports.table import ReportData, build_report_data

_LATEX_SPECIALS = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def latex_escape(text: str) -> str:
    return "".join(_LATEX_SPECIALS.get(ch, ch) for ch in text.replace("\n", " "))


def _tabular(columns: list[str], rows: list[list[str]]) -> list[str]:
    spec = "l" * len(columns)
    lines = [
        rf"\begin{{tabular}}{{{spec}}}",
        r"\hline",
        " & ".join(rf"\textbf{{{latex_escape(c)}}}" for c in columns) + r" \\",
        r"\hline",
    ]
    for row in rows:
        lines.append(" & ".join(latex_escape(cell) for cell in row) + r" \\")
    lines += [r"\hline", r"\end{tabular}"]
    return lines


def render_latex(result: RunResult) -> str:
    """Render a LaTeX report fragment for one run."""
    data: ReportData = build_report_data(result)
    lines: list[str] = [
        f"% {latex_escape(data.title)}",
        "% Generated by eval3r; do not edit by hand.",
        rf"\section*{{{latex_escape(data.title)}}}",
        "",
    ]

    if data.banner is not None:
        lines += [rf"\textbf{{Warning: {latex_escape(data.banner)}}}", ""]

    cov = data.coverage
    partial_txt = r"\textbf{partial}" if cov.partial else "complete"
    lines += [
        rf"\paragraph{{Scene coverage}} {cov.evaluated} of {cov.expected} scenes "
        rf"evaluated, {cov.failed} failed (failure policy: "
        rf"{latex_escape(cov.failure_policy)}); aggregates are {partial_txt}.",
        "",
    ]

    lines += [r"\paragraph{Run configuration}", ""]
    lines += _tabular(["field", "value"], [[k, v] for k, v in data.header])
    lines += [""]

    lines += [r"\paragraph{Aggregate metrics}", ""]
    lines += _tabular(data.aggregate_columns, data.aggregate_rows)
    lines += [""]

    lines += [r"\paragraph{Per-scene metrics}", ""]
    lines += _tabular(data.per_scene_columns, data.per_scene_rows)
    lines += [""]

    if data.failures:
        lines += [r"\paragraph{Failed scenes}", ""]
        lines += _tabular(
            ["scene", "stage", "reason"],
            [[scene, stage, reason] for scene, stage, reason in data.failures],
        )
        lines += [""]

    return "\n".join(lines)


def write_latex_report(result: RunResult, path: Path) -> None:
    """Write ``results.tex`` for one run."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_latex(result), encoding="utf-8")
