site_name: Eval3r
site_description: 3D reconstruction evaluation made explicit.
site_url: https://eval3r.readthedocs.io/
repo_url: https://github.com/xingruiy/eval3r
repo_name: xingruiy/eval3r
edit_uri: edit/main/docs/
docs_dir: .

theme:
  name: readthedocs
  highlightjs: true

nav:
  - Home: index.md
  - Metrics: metric.md
  - Benchmark CLI: benchmark.md
  - Trajectory Formats: trajectory.md
  - Applying Occlusion Masks: apply_masks.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
